// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function CompareTrainingScenes(arg1, arg2) {
  return window['go']['main']['App']['CompareTrainingScenes'](arg1, arg2);
}

export function CreateTrainingPlan(arg1) {
  return window['go']['main']['App']['CreateTrainingPlan'](arg1);
}

export function DeleteRunReplay(arg1) {
  return window['go']['main']['App']['DeleteRunReplay'](arg1);
}

export function DiscoverTrainingContent() {
  return window['go']['main']['App']['DiscoverTrainingContent']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportRunReplay(arg1) {
  return window['go']['main']['App']['ExportRunReplay'](arg1);
}

export function ExportTrainingPlaylist() {
  return window['go']['main']['App']['ExportTrainingPlaylist']();
}

export function GenerateTrainingPlan(arg1) {
  return window['go']['main']['App']['GenerateTrainingPlan'](arg1);
}

export function GetAllBenchmarkProgresses() {
  return window['go']['main']['App']['GetAllBenchmarkProgresses']();
}

export function GetBenchmarkProgress(arg1) {
  return window['go']['main']['App']['GetBenchmarkProgress'](arg1);
}

export function GetBenchmarks() {
  return window['go']['main']['App']['GetBenchmarks']();
}

export function GetCustomThemeCSS() {
  return window['go']['main']['App']['GetCustomThemeCSS']();
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetFavoriteBenchmarks() {
  return window['go']['main']['App']['GetFavoriteBenchmarks']();
}

export function GetLastScenarioScores(arg1) {
  return window['go']['main']['App']['GetLastScenarioScores'](arg1);
}

export function GetPlayedScenarioNames() {
  return window['go']['main']['App']['GetPlayedScenarioNames']();
}

export function GetRecentRuns(arg1) {
  return window['go']['main']['App']['GetRecentRuns'](arg1);
}

export function GetRunPerformanceEvents(arg1) {
  return window['go']['main']['App']['GetRunPerformanceEvents'](arg1);
}

export function GetRunReplay(arg1) {
  return window['go']['main']['App']['GetRunReplay'](arg1);
}

export function GetRunReplayInfo(arg1) {
  return window['go']['main']['App']['GetRunReplayInfo'](arg1);
}

export function GetRunReplayStatus(arg1) {
  return window['go']['main']['App']['GetRunReplayStatus'](arg1);
}

export function GetRunStatsEvents(arg1) {
  return window['go']['main']['App']['GetRunStatsEvents'](arg1);
}

export function GetRunTrace(arg1) {
  return window['go']['main']['App']['GetRunTrace'](arg1);
}

export function GetScenarioTrainingHistory(arg1) {
  return window['go']['main']['App']['GetScenarioTrainingHistory'](arg1);
}

export function GetScreenCaptureInfo() {
  return window['go']['main']['App']['GetScreenCaptureInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTrainingExecution() {
  return window['go']['main']['App']['GetTrainingExecution']();
}

export function GetTrainingGuidance() {
  return window['go']['main']['App']['GetTrainingGuidance']();
}

export function GetTrainingLiveState() {
  return window['go']['main']['App']['GetTrainingLiveState']();
}

export function GetTrainingPlanRunIDs(arg1) {
  return window['go']['main']['App']['GetTrainingPlanRunIDs'](arg1);
}

export function GetTrainingProgress() {
  return window['go']['main']['App']['GetTrainingProgress']();
}

export function GetTrainingSceneRequirements(arg1, arg2) {
  return window['go']['main']['App']['GetTrainingSceneRequirements'](arg1, arg2);
}

export function GetTrainingState() {
  return window['go']['main']['App']['GetTrainingState']();
}

export function GetTrainingWorkbench() {
  return window['go']['main']['App']['GetTrainingWorkbench']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GroupPracticeSessions(arg1) {
  return window['go']['main']['App']['GroupPracticeSessions'](arg1);
}

export function ImportTrainingBenchmarks() {
  return window['go']['main']['App']['ImportTrainingBenchmarks']();
}

export function ImportTrainingPlaylist() {
  return window['go']['main']['App']['ImportTrainingPlaylist']();
}

export function ImportTrainingSource(arg1) {
  return window['go']['main']['App']['ImportTrainingSource'](arg1);
}

export function InstallTrainingPlaylist() {
  return window['go']['main']['App']['InstallTrainingPlaylist']();
}

export function LaunchKovaaksPlaylist(arg1) {
  return window['go']['main']['App']['LaunchKovaaksPlaylist'](arg1);
}

export function LaunchKovaaksScenario(arg1, arg2) {
  return window['go']['main']['App']['LaunchKovaaksScenario'](arg1, arg2);
}

export function OpenCustomThemeCSS() {
  return window['go']['main']['App']['OpenCustomThemeCSS']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RecordTrainingTrialFeedback(arg1, arg2) {
  return window['go']['main']['App']['RecordTrainingTrialFeedback'](arg1, arg2);
}

export function RefreshAllBenchmarkProgresses() {
  return window['go']['main']['App']['RefreshAllBenchmarkProgresses']();
}

export function RefreshTrainingLocal() {
  return window['go']['main']['App']['RefreshTrainingLocal']();
}

export function ResetSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResetSettings'](arg1, arg2, arg3, arg4);
}

export function SaveScenarioNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScenarioNote'](arg1, arg2, arg3);
}

export function SaveSessionNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSessionNote'](arg1, arg2, arg3);
}

export function SaveTrainingSessionNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTrainingSessionNote'](arg1, arg2, arg3, arg4);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetFavoriteBenchmarks(arg1) {
  return window['go']['main']['App']['SetFavoriteBenchmarks'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function TestTrainingReminder() {
  return window['go']['main']['App']['TestTrainingReminder']();
}

export function TrainingAction(arg1) {
  return window['go']['main']['App']['TrainingAction'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTrainingScenario(arg1) {
  return window['go']['main']['App']['UpdateTrainingScenario'](arg1);
}

export function WriteCustomThemeCSS(arg1) {
  return window['go']['main']['App']['WriteCustomThemeCSS'](arg1);
}
