// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {training} from '../models';
import {screen} from '../models';
import {runs} from '../models';
import {sceneanalysis} from '../models';

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function ClearCache():Promise<void>;

export function CompareTrainingScenes(arg1:string,arg2:string):Promise<training.ScenarioComparison>;

export function CreateTrainingPlan(arg1:training.GenerateRequest):Promise<training.Plan>;

export function DeleteRunReplay(arg1:string):Promise<void>;

export function DiscoverTrainingContent():Promise<string>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function ExportRunReplay(arg1:string):Promise<string>;

export function ExportTrainingPlaylist():Promise<string>;

export function GenerateTrainingPlan(arg1:string):Promise<string>;

export function GetAllBenchmarkProgresses():Promise<Record<number, models.BenchmarkProgress>>;

export function GetBenchmarkProgress(arg1:number):Promise<models.BenchmarkProgress>;

export function GetBenchmarks():Promise<Array<models.Benchmark>>;

export function GetCustomThemeCSS():Promise<string>;

export function GetDefaultSettings():Promise<models.Settings>;

export function GetFavoriteBenchmarks():Promise<Array<string>>;

export function GetLastScenarioScores(arg1:string):Promise<Array<models.KovaaksLastScore>>;

export function GetPlayedScenarioNames():Promise<Array<string>>;

export function GetRecentRuns(arg1:number):Promise<Array<models.RunRecord>>;

export function GetRunPerformanceEvents(arg1:string):Promise<Array<models.RunPerformanceEvent>>;

export function GetRunReplay(arg1:string):Promise<string>;

export function GetRunReplayInfo(arg1:string):Promise<screen.ReplayFileInfo>;

export function GetRunReplayStatus(arg1:string):Promise<models.ReplayStatus>;

export function GetRunStatsEvents(arg1:string):Promise<Array<models.RunStatsEvent>>;

export function GetRunTrace(arg1:string):Promise<string>;

export function GetScenarioTrainingHistory(arg1:string):Promise<Array<runs.ScenarioHistoryPoint>>;

export function GetScreenCaptureInfo():Promise<screen.CaptureStatus>;

export function GetSettings():Promise<models.Settings>;

export function GetTrainingExecution():Promise<training.LiveState>;

export function GetTrainingLiveState():Promise<string>;

export function GetTrainingPlanRunIDs(arg1:string):Promise<Array<string>>;

export function GetTrainingProgress():Promise<training.TrainingProgressDTO>;

export function GetTrainingSceneRequirements(arg1:string,arg2:string):Promise<sceneanalysis.Descriptor>;

export function GetTrainingState():Promise<string>;

export function GetTrainingWorkbench():Promise<training.WorkbenchDTO>;

export function GetVersion():Promise<string>;

export function GroupPracticeSessions(arg1:string):Promise<string>;

export function ImportTrainingBenchmarks():Promise<number>;

export function ImportTrainingPlaylist():Promise<number>;

export function ImportTrainingSource(arg1:string):Promise<number>;

export function InstallTrainingPlaylist():Promise<string>;

export function LaunchKovaaksPlaylist(arg1:string):Promise<void>;

export function LaunchKovaaksScenario(arg1:string,arg2:string):Promise<void>;

export function OpenCustomThemeCSS():Promise<void>;

export function QuitApp():Promise<void>;

export function RecordTrainingTrialFeedback(arg1:string,arg2:string):Promise<void>;

export function RefreshAllBenchmarkProgresses():Promise<Record<number, models.BenchmarkProgress>>;

export function RefreshTrainingLocal():Promise<void>;

export function ResetSettings(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;

export function SaveScenarioNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSessionNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveTrainingSessionNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetFavoriteBenchmarks(arg1:Array<string>):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartWatcher(arg1:string):Promise<void>;

export function StopWatcher():Promise<void>;

export function TestTrainingReminder():Promise<void>;

export function TrainingAction(arg1:string):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateTrainingScenario(arg1:string):Promise<void>;

export function WriteCustomThemeCSS(arg1:string):Promise<void>;
